#!/bin/bash

# Kill a process as safely as possible.
# Tries to kill a process using a series of signals with escalating urgency.
# usage: ekill <pid>

# Assign the processid to the first argument.
pid=$1
kill -15 $pid || kill -2 $pid || kill -1 $pid || kill -9 $pid

# If the number of argument is less than 1, exit with a usage statment.
if [[ $# -lt 1 ]]; then
  echo "usage: ekill <pid>"
  exit 1
fi

# Assignthe process id to the first argument.
pid=$1
kill -15 $pid || kill -2 $pid || kill -1 $pid || kill -9 $pid
  
